const defaults={profile:{name:'Your Name',title:'UI/UX Designer & AI Developer',heroTitle:'Designing ideas.<br><span>Building experiences.</span>',bio:'I design clean, user-centered digital products and build technology-driven experiences.',aboutTitle:'Turning concepts into useful digital products.',about:'I am a UI/UX designer with hands-on experience in Figma, wireframing, prototyping and user-centered design.',email:'your.email@example.com',mobile:'1234567890',extra:[]},links:[{title:'LinkedIn',url:'#',place:'contact'},{title:'GitHub',url:'#',place:'contact'},{title:'Figma',url:'#',place:'contact'}],skills:[{name:'UI/UX Design',details:'Figma · Wireframing · Prototyping'},{name:'Product Design',details:'User journeys · Design systems'},{name:'Web Development',details:'HTML · CSS · JavaScript · React'},{name:'Programming',details:'Python · Java'},{name:'AI / ML',details:'AI concepts · ML projects'},{name:'Databases',details:'MongoDB · SQL'},{name:'Tools',details:'Git · GitHub · VS Code'},{name:'Visual Design',details:'Branding · UI systems'}],education:[],experience:[],projects:[{title:'Haptic Scene',description:'AI-powered accessibility concept for communication between people with different communication needs.',tags:['AI','Accessibility','Product'],links:[]},{title:'AI Travel Guide',description:'Travel product concept focused on personalized discovery and a clear user journey.',tags:['UI/UX','Figma','Case Study'],links:[]}],certificates:[],details:[]};
function normalizeProfile(p){const profile={...defaults.profile,...(p||{})};const extras=Array.isArray(profile.extra)?JSON.parse(JSON.stringify(profile.extra)):[];const mobileExtra=extras.find(x=>String(x.label||'').trim().toLowerCase()==='mobile');if(!profile.mobile&&mobileExtra?.value)profile.mobile=mobileExtra.value;profile.extra=extras.filter(x=>String(x.label||'').trim().toLowerCase()!=='mobile');return profile}
function load(){try{const saved=JSON.parse(localStorage.getItem('portfolioData')||'{}');return {profile:normalizeProfile(saved.profile),links:Array.isArray(saved.links)?saved.links:defaults.links,skills:Array.isArray(saved.skills)?saved.skills:defaults.skills,education:Array.isArray(saved.education)?saved.education:[],experience:Array.isArray(saved.experience)?saved.experience:[],projects:Array.isArray(saved.projects)?saved.projects:defaults.projects,certificates:Array.isArray(saved.certificates)?saved.certificates:[],details:Array.isArray(saved.details)?saved.details:[]}}catch{return defaults}}
let d=load(); const esc=s=>String(s==null?'':s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function renderPortfolio(){
const section=(id,label,title,body)=>`<section id="${id}" class="section"><p class="eyebrow">${label}</p><h2>${title}</h2>${body}</section>`;const extra=d.profile.extra||[];const extraCards=(place)=>extra.filter(x=>x.place===place&&x.value).map(x=>{const label=String(x.label||'');const href=x.url||'';const link=href?`<a href="${esc(href)}" target="_blank" rel="noreferrer">${esc(x.value)}</a>`:esc(x.value);return `<div class="profile-extra-item"><b>${esc(label)}</b><span>${link}</span></div>`}).join('');const mobile=d.profile.mobile||'';const mobileLink=mobile?`<div class="profile-extra-item"><b>Mobile</b><span><a href="tel:${esc(String(mobile).replace(/[^0-9+]/g,''))}">${esc(mobile)} 📞</a></span></div>`:'';let html=`<section id="about" class="section split"><div><p class="eyebrow">ABOUT ME</p><h2>${esc(d.profile.aboutTitle)}</h2>${extraCards('about')?`<div class="profile-extra-grid">${extraCards('about')}</div>`:''}</div><div class="text-block"><p>${esc(d.profile.about)}</p></div></section>`;
if(d.skills.length)html+=section('skills','SKILLS','Tools & technologies',`<div class="skills-grid">${d.skills.map(s=>`<div class="skill"><b>${esc(s.name)}</b><small>${esc(s.details)}</small></div>`).join('')}</div>`);
if(d.education.length)html+=section('education','EDUCATION','Education',`<div class="timeline">${d.education.map(e=>`<div class="timeline-item"><span>${esc(e.period)}</span><h3>${esc(e.title)}</h3><p>${esc(e.institution)}${e.board?`<br>${esc(e.board)}`:''}${e.stream?`<br>${esc(e.stream)}`:''}${e.cgpa?`<br><b>CGPA:</b> ${esc(e.cgpa)}`:''}${e.percentage?`<br><b>Percentage:</b> ${esc(e.percentage)}`:''}${e.grade?`<br><b>Grade / Class:</b> ${esc(e.grade)}`:''}${e.description?`<br>${esc(e.description)}`:''}</p>${e.url?`<div class="project-links"><a class="mini-link" href="${esc(e.url)}" target="_blank" rel="noreferrer">View link ↗</a></div>`:''}</div>`).join('')}</div>`);
if(d.experience.length)html+=section('experience','EXPERIENCE','Experience',`<div class="timeline">${d.experience.map(e=>`<div class="timeline-item"><span>${esc(e.period)}</span><h3>${esc(e.title)}</h3><p>${esc(e.company)}${e.description?`<br>${esc(e.description)}`:''}</p></div>`).join('')}</div>`);
if(d.projects.length)html+=section('projects','SELECTED WORK','Projects',`<div class="projects-grid">${d.projects.map((x,i)=>`<article class="project"><div><span class="muted">${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></div><div><div class="tags">${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${(x.links||[]).length?`<div class="project-links">${x.links.map(l=>`<a class="mini-link" href="${esc(l.url)}" target="_blank" rel="noreferrer">${esc(l.title)} ↗</a>`).join('')}</div>`:''}</div></article>`).join('')}</div>`);
if(d.certificates.length)html+=section('certificates','CERTIFICATIONS','Certificates',`<div class="cert-grid">${d.certificates.map(c=>`<div class="cert"><span>${esc(c.date)}</span><h3>${esc(c.title)}</h3><p>${esc(c.issuer)}</p><p>${esc(c.description)}</p>${c.url?`<div class="project-links"><a class="mini-link" href="${esc(c.url)}" target="_blank" rel="noreferrer">View certificate ↗</a></div>`:''}</div>`).join('')}</div>`);
if(d.details.length)html+=section('details','ADDITIONAL DETAILS','More about me',`<div class="details-grid">${d.details.map(x=>`<div class="detail-card"><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p>${x.url?`<div class="project-links"><a class="mini-link" href="${esc(x.url)}" target="_blank" rel="noreferrer">${esc(x.linkTitle||'Open link')} ↗</a></div>`:''}</div>`).join('')}</div>`);
document.getElementById('dynamic').innerHTML=html;document.getElementById('profileName').textContent=d.profile.name||'';document.getElementById('heroEyebrow').textContent=d.profile.title||'UI/UX DESIGNER · AI & SOFTWARE';document.getElementById('heroTitle').innerHTML=d.profile.heroTitle||'';document.getElementById('heroBio').textContent=d.profile.bio||'';const heroExtra=document.getElementById('heroExtra');if(heroExtra)heroExtra.innerHTML=extraCards('hero');document.title=(d.profile.name||'Portfolio')+' | Portfolio';document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('quickLinks').innerHTML=d.links.filter(x=>x.place==='hero').map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">✦ ${esc(x.title)}</a>`).join('');document.getElementById('contactLinks').innerHTML=d.links.filter(x=>x.place==='contact').map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">${esc(x.title)} ↗</a>`).join('')+(d.profile.email?`<a href="mailto:${esc(d.profile.email)}">${esc(d.profile.email)}</a>`:'');const contactExtra=document.getElementById('contactExtra');if(contactExtra)contactExtra.innerHTML=mobileLink+extraCards('contact');
const ids=['about','skills','education','experience','projects','certificates','details','contact'];document.getElementById('nav').innerHTML=ids.filter(id=>document.getElementById(id)).map(id=>`<a href="#${id}">${id[0].toUpperCase()+id.slice(1)}</a>`).join('');document.querySelector('.menu').onclick=()=>document.querySelector('.nav').classList.toggle('open');

}

async function loadFromSupabase(){
  if(!window.supabaseClient) return false;
  try{
    const {data,error}=await window.supabaseClient.from('portfolio').select('data').eq('id',1).maybeSingle();
    if(error || !data || !data.data) return false;
    d={...d,...data.data,profile:normalizeProfile(data.data.profile)};
    renderPortfolio();
    return true;
  }catch(e){ console.warn('Supabase load failed; using local data.',e); return false; }
}
renderPortfolio();
loadFromSupabase();
